/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LegacySequence */

#ifndef _Included_LegacySequence
#define _Included_LegacySequence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LegacySequence
 * Method:    compute
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_LegacySequence_compute
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
